development:
  database: uk_course_map_dev
  adapter: mysql2
  username: root
  password: root
  #host: 192.168.126.67
  host: 127.0.0.1
  encoding: utf8

unistats:
  database: UNISTATS
  adapter: mysql2
  username: root
  password: root
  #host: 192.168.126.67
  host: 127.0.0.1
  encoding: utf8

